### ISSUE TITLE
track specific states during uppy uploads

### ISSUE THREAD

**Issue by thomasreichmann** [thomasreichmann/upload-thomasar#14]
we can use the `useUppyState(uppy, selector)` ([here](https://uppy.io/docs/react/#useuppystateuppy-selector)) to get a lot of info about the current state of the uploads, but it doesn't seem like there are easily accessible info on `uploadSpeed`, parts uploaded, and a few others.

the idea of this issue is to update the useUpload hook to both use that function and `useUppyEvent` (from the same link) to then return to the client a better object containing the upload related states that we actually want.

TBD: What states we actually want, but initially getting current upload speed and parts uploaded/total should be good and provide enough of a base for other ones

**Comment by thomasreichmann** [comment]
found out that we most likely will not be able to use the `useUppyState` at least not without figuring out why it is throwing this error

```text
 ⨯ Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering. at useUpload (./src/app/_hooks/useUpload.ts:31:76) at UploadButton (./src/app/_components/upload/uploadButton.tsx:33:84)
 ```

this doesn't prevent the component from rendering, but it still will prevent us from using it long-term, but since the uppy state doesn't actually have a lot of the info we want, we probably can just ignore it and build our own.
